### ISSUE TITLE
Change SayCel Icon

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#103]
See slide #9 on https://docs.google.com/presentation/d/1w3Ioph9ILnE8ENpgPu7mJSooMA0KljZGofhbGab5r8A/edit#slide=id.g268e53ce06_0_0

Icon on the left is for the dock on the phone
Logo on the right is for splash screen

**Comment by gmarcos87** [comment]
I can not do that, I can only change the icon amd favicon. Spash is managed by google chrome and built according to the data it extracts from the manifest. If it's okay with you, I'll only do it with the icon change

**Comment by rodrigomonelos** [comment]
Ok with changing the icon. Check this Edwin @saycel
