### ISSUE TITLE
Screens in white after deleting contact on Rhizomática version

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#105]
Description: after deleting a contact (on the Rhizomática version of the app) the screen goes white on both tabs (Directory and Call). App has to be closed and opened again.
Expected result: see the directory tab with its content (at least "My number")
Obtained result: screen goes white. Call tab is also white when selected (after switching tabs a couple of times)
Steps to reproduce:

- Create a contact
- Delete the contact

Context
Device: Moto G3
OS and version: Android 6.0.1
Browser and version: Chrome 61.0.3163.98
App version: 000000 not working
Other relevant info: ...

**Comment by rodrigomonelos** [comment]
![screenshot_20171019-114851](https://user-images.githubusercontent.com/26839006/31780493-e47d339a-b4c3-11e7-95bd-a3938ccfd797.png)
![screenshot_20171019-114908](https://user-images.githubusercontent.com/26839006/31780497-e6100e12-b4c3-11e7-8460-10464d658918.png)
![screenshot_20171019-114842](https://user-images.githubusercontent.com/26839006/31780500-e7561b04-b4c3-11e7-96f4-b118ac0ac899.png)

**Comment by gmarcos87** [comment]
Close?

**Comment by rodrigomonelos** [comment]
Diría que todos los que pasé a "Tested and passed" y no tienen comentarios abiertos, vayan a close directamente.
También me estoy dando cuenta de que lo podría haber hecho yo :-p
