### ISSUE TITLE
Audio not going through on App to App calls

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#106]
**Description:** calling app to app (both from laptop and from celphone) audio doesn't go through in some ofcases. I could hear myself calling from my app to my laptop and from rhizo to saycel app on the same phone, but not with Edwin and he cann't with me.
**Expected result:** audio going through
**Obtained result:** audio not going through
Steps to reproduce: 

- Call another app (Edwin on 99910066107)
- Connect the call

**App version:** SayCel HEAD - d828080

**Comment by gmarcos87** [comment]
Maybe we would need a "Check background" label. The app (the frontend) has a very basic interaction with SIP, I think it does not even establish a p2p connection (which could mean that the source of the problem may be in the frontend). If it worked in a situation and not in others maybe there to check what happened behind the server (codecs, timeouts, etc)

**Comment by gmarcos87** [comment]
Close?

**Comment by rodrigomonelos** [comment]
Ok, I close it
