### ISSUE TITLE
Receive notification for new message

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#128]

**Comment by sanchi** [comment]
Currently, a MESSAGE coming in for an offline user sends the same call-incoming push notification as a Call. This should probably be changed so that the app notifications can be specific (e.g. directly show the contents of the Text).

**Comment by gmarcos87** [comment]
HI @sanchi, Can you change the payload you send?:
```'payload': { 'action': 'sms-incoming', 'from': '99910012345', 'content': 'hello world!' }```

**Comment by sanchi** [comment]
ok, I have changed it

**Comment by gmarcos87** [comment]
Works.
