### ISSUE TITLE
Number is presented as "busy" up to 1' after call

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#131]
After finishing a call between A and B, if I call again to any of those during the next ~1', I get the "busy" message.
According to @gmarcos87 the backend is having that delay in registering that the user is offline, and it is causing also a SIP Failure Code when trying to send a message to a number that has just closed his session.
Can you check this @sanchi? Maybe @gmarcos87 can add more details

**Comment by rodrigomonelos** [comment]
At the end of this video recorded by @tcat1 you can see the described behaviour: https://www.youtube.com/watch?v=ZA5ZDcRDcB0

**Comment by rodrigomonelos** [comment]
"When a user closes the app a minute passes until it is recognized as not registered by the backend. In that minute there are these errors in the calls and even in the sms."

**Comment by sanchi** [comment]
I am trying to reproduce, but see only #129 and #133

**Comment by sanchi** [comment]
sorry, really can't reproduce. Maybe it has to do with the way my Android mobile handles the notification? 

Please do he following: 
ssh to rhizortc, I have let kamailio debug log on for now.
run this: 
``` tail -f /var/log/daemon.log > kamailio_log_`date +"%F-%H_%M_%S"`.txt ```
and make two such consecutive calls. Attach the last kamailio_log_xxyyzz.txt to this issue for me to analyze. thanks!

**Comment by sanchi** [comment]
having said that, I can imagine that within that minute, kamailio would try to send over a non-exising websocket connection to the app, and when that fails, it would reply with the error upstream. I have changed the kamailio config to also store that transaction and send a push notification in that case, but I can't test whether that actually works as I can't reproduce with my phone. So please, if you still see this happening, collect a log as noted here, and attach the log for me to fix the config.

**Comment by rodrigomonelos** [comment]
I can not reproduce it now either. 
I can try running those commands anyway but I will need instructions: how do I ssh to rhizortc? 
Also @gmarcos87 can do that easily than me.

Anyway, since we are not being able to reproduce it, I would ask @Tcat1 to check if this issue is still hapenning there Can you? Steps to reproduce are:

- Establish a call from A (GSM) to B (App)
- Finish the call
- Call again from A to B right after having finished the call

**Expected result:**  Call rings on both sides
**Previous result** (what we do not want): Caller gets the __busy__ reply

pd1: where shall we document this debugging instructions for the team? Github wiki? The Site that Marcos created? Google Docs?
pd2: What I do get @sanchi is a __SIP Failure Code__ message on the sms-version of the app when trying to send a message to a user that has just disconnected. Messaging works fine both when both users are online as well as when the one offline has been on that state for more than ~30''. I will create a new issue for that --> #142

**Comment by Tcat1** [comment]
Sorry Folks, No Busy Signal when calling back. In Fact Call Rings and can answer it normally. I can make a video and post it but it may take me a few days to get it uploaded due to slow internet speeds these days...

**Comment by rodrigomonelos** [comment]
Why sorry man? This means that the issue is not there anymore. Or I'm
missing something...

El 22 nov. 2017 7:36 p. m., "Tcat1" <notifications@github.com> escribió:

Sorry Folks, No Busy Signal when calling back. In Fact Call Rings and can
answer it normally. I can make a video and post it but it may take me a few
days to get it uploaded due to slow internet speeds these days...

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/saycel/webph.one/issues/131#issuecomment-346501311>,
or mute
the thread

**Comment by gmarcos87** [comment]
I could not reproduce the error either. @rodrigomonelos this is not the case of Kamailio's delay. That error occurs when the user disconnects, not after a call. With the changes that @sanchi made, the notification arrives but the call was dropped instantly.

**Comment by rodrigomonelos** [comment]
Ok, so we all agree that there is not happening any more that the caller
gets the busy reply when calling someone that has just finished a call,
right?
From the rest of the message it is not clear to me if there is another
issue that need to be addressed. @gmarcos87, can you define the issue (if
there is one) or send me an audio to help me understanding? Thanks


2017-11-24 5:11 GMT-04:00 Marcos Gutierrez <notifications@github.com>:

**Comment by Tcat1** [comment]
Greetings All,

I am still seeing the app is not receiving GSM calls when app is not open.
Now though I see it has been fixed when App is open and call comes in from
GSM Pearl Cel the call does ring and shows incoming call now without having
to touch directory or other buttons on app like it was before in videos I
posted.
I have still not been able to get this busy signal message yet you all talk
about in last email..

**Comment by Tcat1** [comment]
Here is the latest video of GSM to App Calls Not Working when app is not
open. Be sure to also review comments section of this video for more links
to other videos of when GSM to App calls were working ...

https://youtu.be/FTn4jvJhmak

**Comment by Tcat1** [comment]
A video of how GSM to App Calls are being received well now but only when
app is open...

https://youtu.be/qLbXkc9Imc8

**Comment by rodrigomonelos** [comment]
Thanks a lot Thomas. I'm moving this comments to #144 so we follow the specific case
