### ISSUE TITLE
Show options for answering the call

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#133]
App doesn't show the answer/reject opitons.
Originally reported on #119 
https://www.youtube.com/watch?v=ZA5ZDcRDcB0

**Comment by sanchi** [comment]
This one is when the app is open. The push notification has arrived, the phone rings, it sends back 100 Trying and 180 Ringing. 
The answer/reject options only appear when the user clicks e.g. on 'Directory' or 'Share' or somewhere in the screen. It doesn't pop up by itself.

**Comment by gmarcos87** [comment]
I am trying to find the problem, it is due to the update of some of Angular dependencies.

**Comment by gmarcos87** [comment]
It seems to result in commit 3023aac (the current version of the application). Please check if this version does not keep failing. I tried and it seems to work correctly.

**Comment by rodrigomonelos** [comment]
Still not working for me on HEAD - 3023aac

**Comment by rodrigomonelos** [comment]
Can I do something else to help with this?

**Comment by gmarcos87** [comment]
Please try again. The new version is 1aa0ac3. I had to leave many dependencies of Angular fixed that changed the way of compiling the application.

**Comment by rodrigomonelos** [comment]
Tested ok

**Comment by sanchi** [comment]
also tested, ok :)
