### ISSUE TITLE
Rejecting a call results in "Sorry, we could not complete... " because App returns 487

### ISSUE THREAD

**Issue by sanchi** [saycel/webph.one#135]
"487 Request Terminated" is the wrong code to reject a call - this will be sent when receiving CANCEL (when the caller cancels the call). "486 Rejected" or "603 Decline" is the proper one, and it should be interpreted by the App properly on the caller side.

Possibly destroying some JsSip call object on the called side does make JsSip send a 487?

**Comment by gmarcos87** [comment]
Ok, I will change the code

**Comment by sanchi** [comment]
thanks!
