### ISSUE TITLE
After cutting calls in app audio still rings on receivers phone

### ISSUE THREAD

**Issue by Tcat1** [saycel/webph.one#51]
When i was calling with app it was ringing a friends phone when i heard it ring i cut call on app but it continued to ring on their phone

**Comment by rodrigomonelos** [comment]
Moved to the Product Backlog for better priorization
https://docs.google.com/document/d/1BFrZphkxLSyHxd_TajU3FDdh2doYOLs5CRZD9S6QT2c/edit#
