### ISSUE TITLE
Receive calls in background

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#57]
As an app user I need to be able to receive calls, even if the app is in background

**Comment by rodrigomonelos** [comment]
- [x] Trying tasks list to see if they are a good idea

- [ ] For tracking the execution of the tests

**Comment by gmarcos87** [comment]
Fragmentation of push notifications:
- [ ]  Check if the user is registered in the webpush backend when starting the application
- [ ]  Request to show notifications and register user
- [ ]  Show notification when the application is not open and receives a call
- [ ]  Show notification when application is open, but in foreground and recives to call
- [ ]  Reply or reject a notification call
- [ ]  Show a message to the user saying that if you do not accept notifications we can not send incoming calls if the application is not open and active.

**Comment by rodrigomonelos** [comment]
@gmarcos87 creé en el kanban las tarjetas y los issues en los que abrimos esta historia ayer. Propongo cerrar esta y trackeamos sobre las individuales. Son:

- **Ver** notificación cuando la app está en **background** (https://github.com/saycel/webph.one/issues/97)
- **Notificación** con la app **cerrada** (https://github.com/saycel/webph.one/issues/88)
- **Ring** con la app en background (https://github.com/saycel/webph.one/issues/96)
- **Atender** o rechazar la llamada con la app en **back** (https://github.com/saycel/webph.one/issues/94)
- **Atender** o rechazar la llamada con la app **cerrada** (https://github.com/saycel/webph.one/issues/95)
- Pedirle **permiso** al usuario para mostrar notificaciones (https://github.com/saycel/webph.one/issues/89)
- Volver a preguntarle cada vez en caso que las haya rechazado (https://github.com/saycel/webph.one/issues/90)
- Mensaje explicando las implicancias de no aceptar notificaciones (https://github.com/saycel/webph.one/issues/91)
