### ISSUE TITLE
Feedback after the call

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#59]
As SayCel/Rhizo I need to have users feedback from the calls so…

See screen in https://drive.google.com/open?id=1bTp4rkCRTbmGtkETeMht9AFm5GBlAmBrZeXDnFnA9QM

### Acceptance criteria
- [x] Me pide feedback después de cada llamada
- [x] Uso las funcionalidades de la pantalla correctamente
- [x] El feedback se guarda correctamente (rating, opción, texto y número)

**Comment by rodrigomonelos** [comment]
@gmarcos87 la probé, anda piola.
Una pregunta para terminar: cómo puedo ver el feedback que guarda?

Comentarios generales de las pruebas:
- La primera vez se me rompió un poco la pantalla desde el celular cuando elegí agregar comentarios, pero después no volvió a pasar (pantalla adjunta).
- Pienso que preguntar todas las veces puede ser mucho, medio rompe bolas, pero por ahora me parece que va, más que nada para el release. Podemos verlo con Edwin y el feedback de los usuarios.
- Un detalle que le agregaría es una opción para pasar sin contestar (podemos verlo con Edwin, igual se puede responder en blanco) y quizás una para que no te pregunte más (la agregué al Product Backlog), pero pienso que son cosas que podemos dejar para otro momento.
![screenshot_20171012-100737](https://user-images.githubusercontent.com/26839006/31500859-a13526f2-af36-11e7-97cf-f7025c9728a3.png)

**Comment by gmarcos87** [comment]
Tengo que ver el problema asociado al alto de la pantalla cuando aparece el teclado, el mismo error aparece en share. 
Por otro lado, la encuesta aparece solo si la llamada conectó con el server (para no mostrar con cada presión del botón call) y se puede pasar sin responder si presionas la X en la parte superior derecha.,

**Comment by rodrigomonelos** [comment]
Piola lo de la flecha, no lo había visto. 
En esta nueva prueba volvi a ver lo de la pantalla que se rompe. Igual no es grave, se usa.
Aprobado Gutierrez!
