### ISSUE TITLE
Include app version on the feedback record

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#68]

**Comment by rodrigomonelos** [comment]
@gmarcos87 Cómo puedo ver si funciona esto? Hay un link para ver los registros del feedback?

**Comment by rodrigomonelos** [comment]
@gmarcos87 Cómo puedo ver si funciona esto? Hay un link para ver los registros del feedback?

**Comment by rodrigomonelos** [comment]
No entendí por qué lo cerraste

**Comment by gmarcos87** [comment]
It's not this?
![captura de pantalla de 2017-10-23 14-24-15](https://user-images.githubusercontent.com/10773838/31903549-cb74ba7e-b7fe-11e7-83f7-e4c208ada3a3.png)

**Comment by rodrigomonelos** [comment]
No, this item was referring to the feedback given from the share tab
