### ISSUE TITLE
[bug] replying to a call in an inactive app doesn't allow to reply

### ISSUE THREAD

**Issue by nicopace** [saycel/webph.one#76]
# Steps to reproduce

Open the app
send it to background
wait for an incoming call
it will ring, and will appear a notification
click the notification, nothing will happen
switch to the app
the incoming call will be there
click in accept the call

# what should happen

the call gets accepted

# what happens

the ringing keeps on
the call is not accepted
no matter how many times you press the accept button

![screenshot from 2017-10-03 21-07-34](https://user-images.githubusercontent.com/1136597/31141380-f2e2181a-a87f-11e7-8b4f-7d01a16089c9.png)

**Comment by gmarcos87** [comment]
The problem happens when you want to end a session that is terminated by an error or by the remote user. It will be solved in the next pull-request.
