### ISSUE TITLE
Show when call is Connected (instead of "Calling ...")

### ISSUE THREAD

**Issue by sanchi** [saycel/webph.one#81]
Currently, the Overlay still says 'Calling ....' even when connected. This can be very confusing (especially when there's audio issues), as it's not clear to the user whether it really has connected.

**Comment by rodrigomonelos** [comment]
Thanks Stef. It is prioritized and added to the kanban on https://github.com/saycel/webph.one/issues/107. Will close this one to have only one issue to follow.
