### ISSUE TITLE
See an incoming call notification while the app is closed

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#88]
As an app user I need to see a notification when there is an incoming call and the app is closed
Value: to notice that someone is calling me.

Acceptance criteria

- [ ] While having the app instaled but closed and the cell phone locked, when receiving an incoming call, there is a notification that pops up and lets me know that there is a call

Review testing

...?

**Comment by gmarcos87** [comment]
Pasos para testear:
- Abrir la aplicación y obtener el numero de teléfono
- Cerrarla
- Ir a https://webp-test0001.surge.sh
- Completar TO con el número obtenido anteriormente, el FROM el numero que simula estar llamando y en en secretKey la clave secreta de nuestro servicio en el backend (enviada por privado)
- Debe aparecer la notificación en el teléfono o en el navegador

Otra forma de testear es llamar desde otro dispositivo, en este caso se involucran mas actores y resulta difícil obtener un diagnostico claro de posibles errores.

Con estos pasos comprobamos:
- Que el usuario tiene su push notification endpoint registrado en el sistema
- Que el sistema de envíos funciona
- Que el usuario recibe la notificación en su dispositivo

Posibles fallas:
- El 'Test push' no encuentra el usuario ---> Error al registrar la notificación o el usuario no las aceptó
- El usuario no recibe la notificación que si salió ----> Posible bug.

**Comment by rodrigomonelos** [comment]
We observed that, if we try to receive a call after going into the site and accepting to receive notifications but **without having added the icon to the start screen**, when trying to call, the caller just receives a "we can not complete your call at this moment" message. I think this behaviour is interesting to be observed but not critical, since that scenario isn't what we expect, but users to add the icon to desktop. When tried that scenario it worked fine.
