### ISSUE TITLE
Request to show notifications and register user

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#89]
As an app user I need to be asked about receiving notifications so I can accept them and start receiving notifications when there are relevant events (so far calls)

**Acceptance criteria**
- [x] **[Primera instalación]** After the first time I install the app, when I open it, a message apears asking me if I accept to receive notifications.

**Otras preguntas**

- ¿Qué pasa si quiero cancelar el permiso para las notificaciones? (*)
- ¿Hay forma de ver y administrar directamente en el celular estas notificaciones? (*)
   (*) Pasadas al product backlog como "Gestión avanzada de notificaciones desdel dispositivo del usuario"
- ¿Cómo hago para limpiar un celular y hacer pruebas como si fuera la primera vez que uso la app? Respondida debajo por Marcos

**Comment by gmarcos87** [comment]
Si quisieras revocar el permiso de notificaciones (hoy no hay GUI para esa función) se podría hacer. Incluso en el navegador si haces click en el candado de ssl podes gestionar los permisos de cada aplicación web (notificaciones, multimedia, gps, etc)
![captura de pantalla de 2017-10-11 12-34-53](https://user-images.githubusercontent.com/10773838/31450766-a7d33780-ae80-11e7-8d68-16a2abb83626.png)

La "instalación" de la app es solamente un acceso directo en el escritorio con ejecución en pantalla completa (sin la barra de navegación). Por eso cuando borras el icono no estas borrando los datos, esos siguen existiendo en el cache del navegador. Por ende para borrar esos datos podes entrar a la web en el navegador, hacer clic en el candado y luego en ajustes de sitio > Borrar y restablecer. Cuando vuelva a entrar va a ser como la primera vez, sin numero, contactos y permisos.

**Comment by rodrigomonelos** [comment]
**Testeada ok** que pide permiso.

- Separé un ítem relacionado con que se "recuerde la seleccion del usuario" https://github.com/saycel/webph.one/issues/93 para testearlo aparte (lo puse como Done).
- Agregé en el Product Backlog (https://docs.google.com/document/d/1BFrZphkxLSyHxd_TajU3FDdh2doYOLs5CRZD9S6QT2c/edit#) una línea de "Gestión avanzada de notificaciones desde el dispositivo del usuario"
