### ISSUE TITLE
Ask user again about accepting notifications (after denying)

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#90]
As an app user I need to be asked again in case I denied the permision for notifications so I can change my decision.

This message will appear every time the user opens the app in case notifications were rejected. 
This requires the app to check if the user is registered in the webpush backend when starting the application

**Comment by rodrigomonelos** [comment]
This scenario has no sense since when user denies the permision to show notifications, then can not be shown any more. In its place, there is a note for users that denied the permision #91

**Comment by gmarcos87** [comment]
Only for future references: After four ignored requests, Chrome marks the notifications as blocked and does not allow us to request them again. The app will still show the popup with the information for the user but we can not do more than that.
