### ISSUE TITLE
Message for the user explaining the problem with not allowing notifications

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#91]
As an app user I need to be aware that if I do not accept notifications, I will not notice that there are incoming calls unless the app is in foreground, so I can evaluate my decision.
The app shows a message explaining this to the user if he/she denied the permision for showing notifications or just didn't answered to the request.
The message says: "You denied or not answered the request to show notifications. Notifications are necesary for you to know when there is an incoming call. Try to close and open the app again, and accept the request. If it is not showed, follow the instructions on www.saycel.com"

Test cases (acceptance criteria)

- [x] Reject or not answer (tap on X) the request for showing notifications. The message is showed.

- [x] Accept the request for showing notifications. The message is not showed.

**Comment by gmarcos87** [comment]
Bloquear es para que no pregunte nuevamente, la cruz simplemente ignora la petición hasta la próxima ves que sea solicitada. No podemos saber por cual de las dos opciones optó el usuario, simplemente que no tenemos permisos para mostrar push notifications. Toda la GUI está en ingles, no es raro que el mensaje esté en castellano?

**Comment by rodrigomonelos** [comment]
No le podemos bloquear el bloquear?
Ok, entonces le podemos decir que si apretó la cruz, cierre la app y vuelva a abrirla, y que ahi acepte el mensaje. Y para el otro caso qué consejo tenemos, dr?
Definamos y traduzco.

También estoy pensando que cuando abre la app por primera vez desde el acceso directo, ahí le podŕiamos agregar un mensaje que le avise que le va a pedir permiso de micrófono y de notificaciones, que no sea gil y lo acepte.

**Comment by gmarcos87** [comment]
Va a depender de mil factores, lo mejor sería un link a una web con la ayuda ahí redactada.  Es básicamente ir al panel de permisos del navegador (que varía según cual es, que versión y para que dispositivo) y quitar el bloqueo. En el caso de chrome de escritorio es haciendo clic al icono previo a la url y seleccionado "Notificaciones -> Preguntar (predeterminado)" https://support.google.com/chrome/answer/6148059?hl=es-419

La petición de permisos sucede antes, cuando es web. Hay que recordar que lo de que sea "instalable" es un enhancement y no un requerimiento. De otra forma habría que prácticamente bloquear la app hasta que no la instale.

**Comment by rodrigomonelos** [comment]
Ok, pongamos el mensaje hasta ahí con una url de prueba para ver cómo funciona hacer click ahí. Cuando esté la web definida ponemos la url posta.

**Comment by rodrigomonelos** [comment]
Testeado ok el funcionamiento. Me hubiera gustado poder probar qué pasa si hay un link, ver cómo funciona hacer click ahí. No lo agregaste por algo @gmarcos87 ?
