### ISSUE TITLE
[Permisos para notificaciones] Recordar la selección del usuario

### ISSUE THREAD

**Issue by rodrigomonelos** [saycel/webph.one#93]
**[Recordar la selección del usuario]**
- [x] User response to receive notifications is saved on the system.
- [x] Una vez que acepté, cuando vuelvo a iniciar el celular o ingresar a la app después de cerrarla, no me pregunta.
- [x] **[Recordar después de remover]** ¿user response is remembered after removing the app? instalar, aceptar las notificaciones, desinstalar, volver a instalar. Que si no vuelve a preguntar sea porque están aceptadas. O que vuelva a preguntar si había borrado ese registro.
- [x] **[Recordar después de limpiar cache]**

**Comment by gmarcos87** [comment]
Si limpia el caché no hay forma de recordar nada, incluso pierde control sobre el número que tenía asignado. Es distinto cuando solo se borra el acceso al escritorio ya que el caché sigue funcionando en el navegador, por eso recuerda la selección (nunca la borró).
PWA son solo un wrapper de la vista del navegador, siempre el navegador es el origen y destino de los datos.
